// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type Charge struct {
	ID              string                `json:"id"`
	Amount          int64                 `json:"amount"`
	Currency        string                `json:"currency"`
	Status          string                `json:"status"`
	CustomerID      string                `json:"customer_id"`
	PaymentMethodID sql.NullString        `json:"payment_method_id"`
	Description     sql.NullString        `json:"description"`
	Metadata        pqtype.NullRawMessage `json:"metadata"`
	CreatedAt       sql.NullTime          `json:"created_at"`
	UpdatedAt       sql.NullTime          `json:"updated_at"`
}

type Customer struct {
	ID          string                `json:"id"`
	Email       string                `json:"email"`
	Name        string                `json:"name"`
	Phone       sql.NullString        `json:"phone"`
	Description sql.NullString        `json:"description"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	UpdatedAt   sql.NullTime          `json:"updated_at"`
}

type PaymentMethod struct {
	ID              string                `json:"id"`
	Type            string                `json:"type"`
	CustomerID      string                `json:"customer_id"`
	CardLast4       sql.NullString        `json:"card_last4"`
	CardBrand       sql.NullString        `json:"card_brand"`
	CardExpMonth    sql.NullInt32         `json:"card_exp_month"`
	CardExpYear     sql.NullInt32         `json:"card_exp_year"`
	CardFingerprint sql.NullString        `json:"card_fingerprint"`
	Metadata        pqtype.NullRawMessage `json:"metadata"`
	CreatedAt       sql.NullTime          `json:"created_at"`
}

type Refund struct {
	ID        string                `json:"id"`
	ChargeID  string                `json:"charge_id"`
	Amount    int64                 `json:"amount"`
	Currency  string                `json:"currency"`
	Status    string                `json:"status"`
	Reason    sql.NullString        `json:"reason"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	CreatedAt sql.NullTime          `json:"created_at"`
	UpdatedAt sql.NullTime          `json:"updated_at"`
}
