// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateCharge(ctx context.Context, db DBTX, arg CreateChargeParams) (Charge, error)
	CreateCustomer(ctx context.Context, db DBTX, arg CreateCustomerParams) (Customer, error)
	CreatePaymentMethod(ctx context.Context, db DBTX, arg CreatePaymentMethodParams) (PaymentMethod, error)
	CreateRefund(ctx context.Context, db DBTX, arg CreateRefundParams) (Refund, error)
	DeleteCustomer(ctx context.Context, db DBTX, id string) error
	DeletePaymentMethod(ctx context.Context, db DBTX, arg DeletePaymentMethodParams) error
	GetCharge(ctx context.Context, db DBTX, id string) (Charge, error)
	GetChargeStats(ctx context.Context, db DBTX) (GetChargeStatsRow, error)
	GetCustomer(ctx context.Context, db DBTX, id string) (Customer, error)
	GetCustomerByEmail(ctx context.Context, db DBTX, email string) (Customer, error)
	GetCustomerStats(ctx context.Context, db DBTX) (GetCustomerStatsRow, error)
	GetPaymentMethod(ctx context.Context, db DBTX, id string) (PaymentMethod, error)
	GetRefund(ctx context.Context, db DBTX, id string) (Refund, error)
	GetRefundStats(ctx context.Context, db DBTX) (GetRefundStatsRow, error)
	ListAllCharges(ctx context.Context, db DBTX, arg ListAllChargesParams) ([]Charge, error)
	ListAllRefunds(ctx context.Context, db DBTX, arg ListAllRefundsParams) ([]Refund, error)
	ListCharges(ctx context.Context, db DBTX, arg ListChargesParams) ([]Charge, error)
	ListCustomers(ctx context.Context, db DBTX, arg ListCustomersParams) ([]Customer, error)
	ListPaymentMethods(ctx context.Context, db DBTX, customerID string) ([]PaymentMethod, error)
	ListRefunds(ctx context.Context, db DBTX, arg ListRefundsParams) ([]Refund, error)
	UpdateChargeStatus(ctx context.Context, db DBTX, arg UpdateChargeStatusParams) (Charge, error)
	UpdateCustomer(ctx context.Context, db DBTX, arg UpdateCustomerParams) (Customer, error)
	UpdateRefundStatus(ctx context.Context, db DBTX, arg UpdateRefundStatusParams) (Refund, error)
}

var _ Querier = (*Queries)(nil)
